"""Portable evidence receipts for incident review and postmortems."""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict
from typing import Any

from .models import IncidentPlan
from .policy import ResponsePolicy


def plan_dict(plan: IncidentPlan, policy: ResponsePolicy) -> dict[str, Any]:
    signal = asdict(plan.signal)
    signal["observed_at"] = plan.signal.observed_at.isoformat()
    payload = {
        "incident_id": plan.incident_id,
        "status": "awaiting_approval",
        "signal": signal,
        "summary": plan.summary,
        "decision": {
            "action": plan.action,
            "confidence": plan.confidence,
            "policy": policy.as_dict(),
        },
        "findings": [
            {
                "asset": asdict(finding.evidence.asset),
                "hops": finding.evidence.hops,
                "path": finding.evidence.path,
                "matched_field": finding.evidence.matched_field,
                "score": finding.score,
                "reasons": finding.reasons,
            }
            for finding in plan.findings
        ],
        "mutations": [asdict(mutation) for mutation in plan.mutations],
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    payload["receipt_sha256"] = hashlib.sha256(canonical.encode()).hexdigest()
    return payload


def receipt_json(plan: IncidentPlan, policy: ResponsePolicy) -> str:
    return json.dumps(plan_dict(plan, policy), indent=2, default=str)


def receipt_markdown(plan: IncidentPlan, policy: ResponsePolicy) -> str:
    lines = [
        f"# {plan.incident_id} — FAULTLINE evidence receipt",
        "",
        f"**Recommended action:** {plan.action.value.upper()}<br>",
        f"**Confidence:** {plan.confidence:.0%}<br>",
        f"**Observed:** {plan.signal.observed_at.isoformat()}<br>",
        f"**Source:** `{plan.signal.source_urn}`",
        f"**Receipt seal:** `{plan_dict(plan, policy)['receipt_sha256']}`",
        "",
        "## Executive summary",
        "",
        plan.summary,
        "",
        "## Traceable evidence",
        "",
        "| Risk | Asset | Type | Hops | Confirmed field |",
        "| ---: | --- | --- | ---: | --- |",
    ]
    for finding in plan.findings:
        evidence = finding.evidence
        lines.append(
            f"| {finding.score} | {evidence.asset.name} | {evidence.asset.entity_type} "
            f"| {evidence.hops} | {evidence.matched_field or '—'} |"
        )
    lines.extend(["", "## Reasoning ledger", ""])
    for finding in plan.findings:
        lines.append(f"### {finding.evidence.asset.name} — {finding.score}/100")
        lines.extend(f"- {reason}" for reason in finding.reasons)
        lines.append(f"- Path: `{' → '.join(finding.evidence.path)}`")
        lines.append("")
    lines.extend(
        [
            "## Governed write-back plan",
            "",
            "No catalog mutation is executed until a human explicitly approves this plan.",
            "",
        ]
    )
    for index, mutation in enumerate(plan.mutations, 1):
        lines.append(
            f"{index}. **{mutation.kind.value}** on `{mutation.target_urn}` — "
            f"{mutation.reason}"
        )
    lines.extend(
        [
            "",
            "## Policy snapshot",
            "",
            "```json",
            json.dumps(policy.as_dict(), indent=2),
            "```",
            "",
            "_Generated by FAULTLINE. The receipt contains deterministic evidence, not hidden "
            "chain-of-thought._",
        ]
    )
    return "\n".join(lines)
